### ISSUE TITLE
How to use the test_net.py?

### ISSUE THREAD

**Issue by AmingWu** [jiaxi-wu/MPSR#8]
Thanks for your good work.

Could you tell me how to use test_net.py to evaluate the trained models?

**Comment by jiaxi-wu** [comment]
1. If your trained models is `model.pth`, do: `echo ./model.pth > last_checkpoint`.
2. With your aim cfg file (e.g. configs/fewshot/standard/e2e_voc_split1_10shot_finetune.yaml), run: 
```
export CUDA_VISIBLE_DEVICES=0,1 
export NGPUS=2 
python -m torch.distributed.launch --nproc_per_node=$NGPUS ./tools/test_net.py --config-file "configs/fewshot/standard/e2e_voc_split1_10shot_finetune.yaml"
```
This should help you for evaluation.

**Comment by AmingWu** [comment]
Thanks for your reply. I find the finetune models contain model_voc_split1_base.pth and voc0712_split1base_pretrained.pth. Should I run this code, i.e., cat ./voc0712_split1base_pretrained.pth > last_checkpoint?

**Comment by jiaxi-wu** [comment]
`model_voc_split1_base.pth` is the model trained on 15 classes. We replace the last classification layer of it to generate `voc0712_split1base_pretrained.pth`. So you need to run `echo ./model_voc_split1_base.pth > last_checkpoint`.
While the corresponding cfg file is `configs/fewshot/base/e2e_voc_split1_base.yaml`.

**Comment by AmingWu** [comment]
I am confused. After running python tools/fewshot_exp/cal_novel_voc.py fs_exp/voc_standard_results, I can obtain the evaluation result. Now I want to use test_net.py to reproduce the result generated by python tools/fewshot_exp/cal_novel_voc.py fs_exp/voc_standard_results. For this case, is it right to run echo ./model_voc_split1_base.pth > last_checkpoint?

**Comment by jiaxi-wu** [comment]
Oh I got u.
In `tools/fewshot_exp/train_voc_standard.sh`  line14, we delete these models after fine-tuning. You should modify this line to get the last model of every few-shot exp, e.g. `mv model_final.pth model_split${split}_${shot}shot.pth`.

**Comment by AmingWu** [comment]
Thank you very much. Should I modify  rm last_checkpoint？

**Comment by jiaxi-wu** [comment]
No. `maskrcnn-benchmark` use the last_checkpoint for model reloading.

**Comment by AmingWu** [comment]
![QQ截图20200805084043](https://user-images.githubusercontent.com/38445175/89359017-664fe680-d6f7-11ea-81ed-d3cf54e9c1c6.png)
Thank you very much. I have obtained the finetuned models. However, When I use test_net.py, there is an error.

**Comment by AmingWu** [comment]
export CUDA_VISIBLE_DEVICES=0,1
export NGPUS=2
SPLIT=(1 2 3)
SHOT=(10 5 3 2 1)
mkdir fs_exp/voc_standard_results
for shot in ${SHOT[*]} 
do
  for split in ${SPLIT[*]} 
  do
    configfile=configs/fewshot/standard_test/e2e_voc_split${split}_${shot}shot_finetune.yaml
    python -m torch.distributed.launch --nproc_per_node=$NGPUS ./tools/test_net.py --config-file ${configfile}
  done
done
python tools/fewshot_exp/cal_novel_voc.py

**Comment by AmingWu** [comment]
This is the error.
![QQ截图20200805084521](https://user-images.githubusercontent.com/38445175/89359298-0ad22880-d6f8-11ea-856e-1fef4e692ebf.png)

**Comment by jiaxi-wu** [comment]
Hi~ @AmingWu 
1. The evaluation was done after training each datasplit by default and the results were saved in `fs_exp/voc_standard_results`. You can find them easily and run `python tools/fewshot_exp/cal_novel_voc.py fs_exp/voc_standard_results` for a quick summary.
2. The script you provide lacks lines: 
`echo ./model_split${split}_${shot}shot.pth > last_checkpoint` before test_test.
`mv inference/voc_2007_test/result.txt fs_exp/voc_standard_results/result_split${split}_${shot}shot.txt` after test_net.
`python tools/fewshot_exp/cal_novel_voc.py fs_exp/voc_standard_results` last line.

Hope this will help you.

**Comment by AmingWu** [comment]
Thank you very much. I have solved this problem.

**Comment by HuangLian126** [comment]
@AmingWu  How do you get the finetuned models? I run the "bash tools/fewshot_exp/train_voc_standard.sh", however get these errors. It seems that I try to load the "model_voc_split1_base.pth"  instead of  "voc0712_split1base_pretrained.pth".  I do not why?

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Traceback (most recent call last):
  File "./tools/train_net.py", line 220, in <module>
    main()
  File "./tools/train_net.py", line 213, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "./tools/train_net.py", line 90, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/hl/hl/MPSR-master/maskrcnn_benchmark/utils/checkpoint.py", line 66, in load
    self._load_model(checkpoint)
  File "/home/hl/hl/MPSR-master/maskrcnn_benchmark/utils/checkpoint.py", line 103, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"))
  File "/home/hl/hl/MPSR-master/maskrcnn_benchmark/utils/model_serialization.py", line 81, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([16, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([21]).
Traceback (most recent call last):
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hl/anaconda3/envs/python37/bin/python', '-u', './tools/train_net.py', '--local_rank=0', '--config-file', 'configs/fewshot/standard/e2e_voc_split1_1shot_finetune.yaml']' returned non-zero exit status 1.
rm: 无法删除'model_final.pth': 没有那个文件或目录
rm: 无法删除'last_checkpoint': 没有那个文件或目录
mv: 无法获取'inference/voc_2007_test/result.txt' 的文件状态(stat): 没有那个文件或目录
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
