### ISSUE TITLE
some issues about command ''bash tools/fewshot_exp/train_voc_standard.sh''

### ISSUE THREAD

**Issue by HuangLian126** [jiaxi-wu/MPSR#9]
I have trained the base class with the command ''bash tools/fewshot_exp/train_voc_base.sh'', then get some issues when running command ''bash tools/fewshot_exp/train_voc_standard.sh'':

RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([16, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([21]).

16 is the numbers of base class and background, and 21 is the the numbers of all class and background. I do not know why?

**Comment by jiaxi-wu** [comment]
It seems that you are trying to load "model_voc_split*_base.pth" during fine-tuning. Check the file `last_checkpoint` and delete it.

**Comment by HuangLian126** [comment]
There is no file ''last_checkpoint''

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
Traceback (most recent call last):
  File "./tools/train_net.py", line 194, in <module>
    main()
  File "./tools/train_net.py", line 187, in main
    model = train(cfg, args.local_rank, args.distributed)
  File "./tools/train_net.py", line 65, in train
    extra_checkpoint_data = checkpointer.load(cfg.MODEL.WEIGHT)
  File "/home/hl/hl/MPSR-master/maskrcnn_benchmark/utils/checkpoint.py", line 62, in load
    self._load_model(checkpoint)
  File "/home/hl/hl/MPSR-master/maskrcnn_benchmark/utils/checkpoint.py", line 98, in _load_model
    load_state_dict(self.model, checkpoint.pop("model"))
  File "/home/hl/hl/MPSR-master/maskrcnn_benchmark/utils/model_serialization.py", line 80, in load_state_dict
    model.load_state_dict(model_state_dict)
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 839, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([16, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([21]).
Traceback (most recent call last):
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/site-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/home/hl/anaconda3/envs/python37/lib/python3.7/site-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hl/anaconda3/envs/python37/bin/python', '-u', './tools/train_net.py', '--local_rank=0', '--config-file', 'configs/fewshot/standard/e2e_voc_split1_1shot_finetune.yaml']' returned non-zero exit status 1.
rm: 无法删除'model_final.pth': 没有那个文件或目录
rm: 无法删除'last_checkpoint': 没有那个文件或目录
mv: 无法获取'inference/voc_2007_test/result.txt' 的文件状态(stat): 没有那个文件或目录
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


my file "e2e_voc_split1_1shot_finetune.yaml " is : 

MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  #WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  WEIGHT: "/home/hl/hl/MPSR-master/voc0712_split1base_pretrained.pth"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 8
    NUM_CLASSES: 21
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("voc_2007_trainval_1shot_standard", "voc_2012_trainval_1shot_standard")
  CLOSEUP: ("voc_2007_trainval_closeup_standard", "voc_2012_trainval_closeup_standard")
  TEST: ("voc_2007_test",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (1300, 1700)
  MAX_ITER: 2000
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 1


Can you help me?

**Comment by jiaxi-wu** [comment]
Can you check the last classification layer of "/home/hl/hl/MPSR-master/voc0712_split1base_pretrained.pth"? 
It should be 
```
'module.roi_heads.box.predictor.cls_score.weight':  torch.Size([21, 1024]), 
'module.roi_heads.box.predictor.cls_score.bias': torch.Size([21])
```
If not, rerun the command: "python tools/fewshot_exp/trans_voc_pretrained.py ${split}".

**Comment by HuangLian126** [comment]
I check the last classification layer of my "/home/hl/hl/MPSR-master/voc0712_split1base_pretrained.pth".
 It is 
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
roi_heads.box.predictor.cls_score.weight torch.Size([16, 1024])
roi_heads.box.predictor.cls_score.bias torch.Size([16])
roi_heads.box.predictor.bbox_pred.weight torch.Size([4, 1024])
roi_heads.box.predictor.bbox_pred.bias torch.Size([4])
module.roi_heads.box.predictor.cls_score.weight torch.Size([21, 1024])
module.roi_heads.box.predictor.cls_score.bias torch.Size([21])
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

I still have these issues:
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
	size mismatch for roi_heads.box.predictor.cls_score.weight: copying a param with shape torch.Size([16, 1024]) from checkpoint, the shape in current model is torch.Size([21, 1024]).
	size mismatch for roi_heads.box.predictor.cls_score.bias: copying a param with shape torch.Size([16]) from checkpoint, the shape in current model is torch.Size([21]).
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

Should  the "roi_heads.box.predictor.cls_score.weight torch.Size([16, 1024])" and "roi_heads.box.predictor.cls_score.bias torch.Size([16])"  be modified to the torch.Size([21, 1024]) and torch.Size([21])?  It is so strange!

**Comment by jiaxi-wu** [comment]
I guess you are using PyTorch of a latest version. Or some mistakes happened.
Modify the `tools/fewshot_exp/trans_voc_pretrained.py` and run it again:
line 8: replace `module.roi_heads.box.predictor.cls_score.weight` with `roi_heads.box.predictor.cls_score.weight`,
line 9: replace `module.roi_heads.box.predictor.cls_score.bias` with `roi_heads.box.predictor.cls_score.bias`.

**Comment by HuangLian126** [comment]
Thank you very much, it works.  Can you tell me your WeChat for academic exchange?

**Comment by topdou96** [comment]
您好 在我做如下操作：
line 8: replace module.roi_heads.box.predictor.cls_score.weight with roi_heads.box.predictor.cls_score.weight,
line 9: replace module.roi_heads.box.predictor.cls_score.bias with roi_heads.box.predictor.cls_score.bias.
之后，是重新执行train_voc_base.sh，还是直接执行train_voc_standard.sh呢
如果我直接执行train_voc_standard.sh，还是会报相同的错误
